"""Initial migration

Revision ID: 1dd253515efe
Revises: 
Create Date: 2024-11-12 19:36:57.879012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd253515efe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('item_features', sa.String(), nullable=False),
    sa.Column('item_price', sa.Integer(), nullable=False),
    sa.Column('item_prev_price', sa.Integer(), nullable=True),
    sa.Column('item_image_url', sa.Text(), nullable=False),
    sa.Column('item_category', sa.String(), nullable=False),
    sa.Column('items_in_stock', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_name')
    )
    op.create_table('special_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('item_special_categories',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('special_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_special_categories_item_id_items')),
    sa.ForeignKeyConstraint(['special_category_id'], ['special_categories.id'], name=op.f('fk_item_special_categories_special_category_id_special_categories')),
    sa.PrimaryKeyConstraint('item_id', 'special_category_id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_reviews_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('item_special_categories')
    op.drop_table('users')
    op.drop_table('special_categories')
    op.drop_table('items')
    # ### end Alembic commands ###
